### PR TITLE
HRQB 43 - add production build yaml github action

### PR DESCRIPTION
**Pull request by ghukill**
### Purpose and background context

Adds production build github action.

### Includes new or updated dependencies?
NO

### Changes expectations for external applications?
YES: production ECR images will be built on tagged releases

### What are the relevant tickets?
- https://mitlibraries.atlassian.net/browse/HRQB-43

### Developer
- [X] All new ENV is documented in README
- [X] All new ENV has been added to staging and production environments
- [X] All related Jira tickets are linked in commit message(s)
- [X] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer(s)
- [x] The commit message is clear and follows our guidelines (not just this PR message)
- [x] There are appropriate tests covering any new functionality
- [x] The provided documentation is sufficient for understanding any new functionality introduced
- [x] Any manual tests have been performed **or** provided examples verified
- [x] New dependencies are appropriate or there were no changes

### CODE REVIEW

**Review by vab — APPROVED** [review]
lgtm

**Review by zotoMIT — CHANGES_REQUESTED** [review]
to conform with other repos, it should be named `prod-promote.yml` instead of `prod-build.yml` as noted in the text of the file.

**Comment by ghukill** [comment]
> to conform with other repos, it should be named `prod-promote.yml` instead of `prod-build.yml` as noted in the text of the file.

Thanks for catching that @zotoMIT - updated and re-requested review.

**Review by zotoMIT — APPROVED** [review]
LGTM

**Pull request merged**
